version: '3.8'

services: 
  hotjb-server:
    image: chaosannals/hotjb:0.1.0
    container_name: hotjb-server
    ports: 
      - 30000:30000
    volumes:
      - ./config:/app/config
      - ./runtime:/app/runtime
    networks: 
      - hotjb-net

networks: 
  hotjb-net:
    name: hotjb-net
    driver: bridge
    